apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zomato
  name: zomato-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: cont1
        image: rahamshaik/zomato_new:c656e1a7c80225dd5aeaefb7c31e8a5cb257a75b
        ports:
          - containerPort: 3000



