apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movie
  name: movie-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: cont1
        image: venky98765/movies:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: movie
  ports:
    - port: 80
      targetPort: 80
